# This is a basic workflow to help you get started with Actions

name: Stale PRs Slack Notification

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
     - cron: '0/10 * * * 1-5'
  workflow_dispatch:
     
permissions:
#     issues: write
    pull-requests: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build
  notify_stale_pr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Label Stale Issues
        uses: actions/stale@v4.0.0
        with:
          # The message to post on the issue when closing it. If none provided, will not comment when closing an issue"
          stale-pr-message: 'No activity for last 1 day'
          # The number of days old an issue or a pull request can be before marking it stale. Set to -1 to never mark issues or pull requests as stale automatically.
          days-before-stale: -1
          # The number of days old a pull request can be before marking it stale. Set to -1 to never mark pull requests as stale automatically. Override "days-before-stale" option regarding only the pull requests.
          days-before-pr-stale: 1
          # The number of days to wait to close an issue or a pull request after it being marked stale. Set to -1 to never close stale issues or pull requests.
          days-before-close: -1
          # The number of days to wait to close an issue after it being marked stale. Set to -1 to never close stale issues. Override "days-before-close" option regarding only the issues.
          stale-pr-label: 'stale'
          remove-stale-when-updated: true
          remove-issue-stale-when-updated: false
